name: Releases

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - run: |
        mv .github/build/Makefile .
        make
        rm -rf dist
        mkdir dist

    - name: Package
      run: tar -czvf dist/pastebin-linux-amd64.tar.gz pastebin

    - name: Package Arch Linux
      run: |
        mv pastebin .github/pkg
        v=$(git describe --abbrev=0 --tags)
        sed s/pkgver=/pkgver=$v/ -i .github/pkg/PKGBUILD
        docker build --output=dist/ .github/pkg

    - uses: softprops/action-gh-release@v2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: dist/*
