name: Releases

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - run: make

    - run: |
        mkdir dist
        tar -czvf dist/pastebin-linux-amd64.tar.gz pastebin

    - uses: softprops/action-gh-release@v2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: dist/*
